# Generated by Django 5.1.7 on 2025-05-26 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaires', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('path', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('progressing', 'Progressing'), ('completed', 'Completed')], default='open', max_length=20)),
                ('progression', models.FloatField(default=0.0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('theme', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('progressing', 'Progressing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='progressing', max_length=20)),
                ('is_finished', models.BooleanField(default=False)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stagiaires.instructor')),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stagiaires.intern')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('room', models.CharField(max_length=100)),
                ('subjects', models.JSONField(default=list)),
                ('status', models.CharField(max_length=100)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stagiaires.internship')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed')], default='draft', max_length=20)),
                ('comments', models.JSONField(default=list)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stagiaires.document')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stagiaires.interview')),
            ],
        ),
        migrations.CreateModel(
            name='ReportTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stagiaires.report')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('progressing', 'Progressing'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stagiaires.intern')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stagiaires.task')),
            ],
        ),
        migrations.CreateModel(
            name='WorkHoursLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('hours_worked', models.FloatField()),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stagiaires.intern')),
            ],
        ),
    ]
