# Generated by Django 5.1.4 on 2025-05-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaires', '0003_alter_interview_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmenttask',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
