# Generated by Django 5.1.4 on 2025-05-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaires', '0004_assignmenttask_completed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='submitted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
