# Generated by Django 5.1.4 on 2025-05-27 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaires', '0005_report_submitted_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmenttask',
            name='task',
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stagiaires.internship')),
            ],
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stagiaires.project')),
            ],
        ),
    ]
