# Generated by Django 5.1.4 on 2025-06-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaires', '0007_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='type',
            field=models.CharField(choices=[('hiring', 'Hiring'), ('academic', 'Academic')], default='academic', max_length=20),
        ),
    ]
