# Generated by Django 5.1.4 on 2025-06-08 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaires', '0008_internship_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmenttask',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='assignmenttask',
            name='status',
        ),
        migrations.AddField(
            model_name='assignmenttask',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stagiaires.task'),
        ),
    ]
