# Generated by Django 5.1.4 on 2025-06-09 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaires', '0009_remove_assignmenttask_priority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='internship',
        ),
        migrations.AddField(
            model_name='project',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stagiaires.instructor'),
        ),
        migrations.AddField(
            model_name='project',
            name='intern',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stagiaires.intern'),
        ),
    ]
