# Generated by Django 5.1.4 on 2025-06-09 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaires', '0010_remove_project_internship_project_instructor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='project',
            name='intern',
        ),
        migrations.AddField(
            model_name='project',
            name='internship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stagiaires.internship'),
        ),
    ]
