# Generated by Django 5.1.4 on 2025-06-10 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaires', '0011_remove_project_instructor_remove_project_intern_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervised_assignments', to='stagiaires.instructor')),
                ('intern', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='stagiaires.intern')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='stagiaires.project')),
            ],
        ),
    ]
